server:
  port: 9080

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
app:
  pulsar:
    topic:
      job-command-job-a: persistent://public/default/job-command-JOB_A
      job-completed: persistent://public/default/job-completed
